### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by larshp** [bayersglassey/abippity-sapiness#2]
what is the license for this code?

see https://help.github.com/en/articles/adding-a-license-to-a-repository

**Comment by bayersglassey** [comment]
I added a simple file.
It's not one of the well-known ones like MIT because I have no idea what's proper to use in a reverse-engineering project.

**Comment by larshp** [comment]
For Europe, see https://www.computerworld.com/article/2503557/programming-languages-can-t-have-copyright-protection--eu-court-rules.html

not sure about the US

**Comment by bayersglassey** [comment]
Ah, nice. I'm in Canada, but I'm sure my less-than-1000-or-so lines of
Python will be safe from legal retribution from SAP SE in any case.
Fork at your own risk, I suppose!
